#!/bin/bash
#
# generate a zone file from small source file snippets: file name = host, file content = ip
#

# where to put the new zone file
ZONEFILE=/home/dns-update/zones/dynip.example.com.zone

# where to find the source snippets
SOURCEDIR=/home/dns-update/hosts

# beware: further configuration ahead in the <<HERE_DOCUMENT!

# back up zone file if current file exists and has contents
if [ -f "${ZONEFILE}" -a -s "${ZONEFILE}" ] ; then
    mv "${ZONEFILE}" "${ZONEFILE}.bak"
fi

# generate serial
SERIAL=$(date +%Y%m%d%H%M%S)

# generate new zone file
cat > "${ZONEFILE}" <<EOF
\$ORIGIN dynip.example.com.                           ; designates the start of this zone file in the namespace
\$TTL   1m                                            ; default expiration time of all resource records without their own TTL value

dynip.example.com.         IN  SOA  ns.example.com. hostmaster.example.com. (
                                    ${SERIAL}   ;serial
                                    60               ;minimum refresh 60 seconds
                                    60               ;retry every 60 seconds
                                    60               ;expire after 60 seconds
                                    60               ;minimum 60 seconds
                                    )
dynip.example.com.         NS       ns.example.com.  ;ns.example.com is a nameserver for dynip.example.com.

static                     A        127.0.0.1        ;reflecting example entry

; dynamically generated entries follow:
EOF

# find nicely formatted host files and append them (IPv4 only for now)
# (please: no line breaks in file names - DNS does not support this anyway)
# TODO: simple check for valid hostnames
# TODO: more complete check for IP addresses, this currently allows "999.555.333.111" like seen on TV
grep -HE '^[[:digit:]]{1,3}\.[[:digit:]]{1,3}\.[[:digit:]]{1,3}\.[[:digit:]]{1,3}$' "${SOURCEDIR}"/* \
| sort \
| sed 's/:/ /' \
| while read FILENAME IPADDRESS; do
    HOSTNAME="$(basename "${FILENAME}")"
    printf '%-32s A %-15s ;\n' "${HOSTNAME}" "${IPADDRESS}"
done >> "${ZONEFILE}"
